import Head from 'next/head'
import Box from '@mui/material/Box';

export default function BoxHead(props) {
    const { title = '', children } = props;
    const textTitle = title ? `Nama Apps - ${title}` : 'Nama Apps'
    return (
        <Box
            sx={{
                display: 'flex',
                flexDirection: 'column',
                bgcolor: 'background.paper',
                minHeight: '100vh',
            }}>
            <Head>
                <title>{textTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </Box>
    )
}